### PR TITLE
21 masked array lost issue 126

### PR DESCRIPTION
**Pull request by mcrot**
I'm trying to fix issue #126, but it turns out to be non-trivial for me.

I've added new tests which show the problem, that the masked array is lost for scaled topographies
when writing to NetCDF. (There is also another problem with nonuniform line scans but let's skip that for now.)
See this branch for the tests.

It seems that `scipy.io.netcdf.netcdf_variable.__setitem__` does not always the right thing
on 
```python
heights_var[...] = topography.heights()  #  see NC.py, line 403 (currently)
```
but only in case the topography is scaled (doesn't matter if detrended).

When digging deeper this line
```python
self.data[index] = data   # scipy.io.netcdf.py, line 1015
```
simply looses the mask and fills in some value.
Unfortunately the final code is compiled C and can't be debugged further so easily.

@pastewka , do you have an idea what's going on here or how I can proceed the debugging?

I could open an issue on scipy, but it's difficult to specify when this happens without the `SurfaceTopography` context.
I don't know yet what is different here in case of scaled topographies.

### CODE REVIEW

**Comment by mcrot** [comment]
You can simply debug the first failing test in order to see what I mean.

**Comment by mcrot** [comment]
There is a switch `maskandscale` for scipy's netCDF datasets which can be set to `True but then the mask is always lost.
The datasets of the `netCDF4` have more options, but I don't know yet whether would help.

**Comment by pastewka** [comment]
I am currently looking at this. I fixed a couple of issues, and it work in principle.

What does not work is writing with `NetCDF4` and reading with `scipy`. The reason is apparently because `netcdf_file` writes the `_FillValue` for masked arrays explicity into the file, which `netCDF4` does not.

**Comment by pastewka** [comment]
I created an issue for the mask problem here: https://github.com/scipy/scipy/issues/14566

**Comment by pastewka** [comment]
I think this should fix the issue

**Comment by pastewka** [comment]
Hi @mcrot - can you check whether this fulfills the requirements for fixing #126 ?

**Comment by mcrot** [comment]
Yes, I'll let you know, thanks for the fix.

**Comment by mcrot** [comment]
The tests run, but there excluded test cases for one-dimensional non-uniform topographies.
If I include them, then those tests still fail. So this would fix the original issue https://github.com/ContactEngineering/TopoBank/issues/699, but it could still cause problems in the web app, I think. Is 1D+non-uniform excluded on purpose?

Maybe I can fix it, I'll have a look.

**Comment by pastewka** [comment]
1D, nonuniform topographies cannot have missing data and should not be represented by masked arrays.

**Comment by mcrot** [comment]
Okay, thanks - I didn't know whether this somehow could result from measurements.

**Comment by mcrot** [comment]
Probably it's better to let such files explicitly fail while loading them. So we are sure we never have to deal with this case.

**Comment by pastewka** [comment]
It is not inconceivable, but I think this would need to be supported by `NonuniformLineScan` directly somehow. Since we don't have any use case for this at present I would not preemptively plan for it.

**Comment by mcrot** [comment]
Yes, I would not plan for it, but since the web app would calculate wrong results for 1D non-uniform data with missing points at the moment, I would feel safer to just let it fail at some point. Then we would also become aware that we need to implement this.

**Comment by pastewka** [comment]
Okay, let me add a check for masked arrays into `NonuniformLineScan`...

**Comment by mcrot** [comment]
I confirm that when I install this PR's branch in the environment of my web app, and renew the netcdf files, then https://github.com/ContactEngineering/TopoBank/issues/699 is fixed.

**Comment by pastewka** [comment]
I've added a guard that raises an error when a nonuniform line scan is initialized with masked arrays

**Review by pastewka — APPROVED** [review]

**Comment by pastewka** [comment]
@mcrot - I've created release 0.95.2 that contains this fix

**Pull request merged**
