### PR TITLE
API: Error reporting via exceptions

### PR DESCRIPTION
**Pull request by pastewka**
…alysis function now raise errors upon encountering reentrant topographies or topographies with no reliable data

### CODE REVIEW

**Comment by pastewka** [comment]
Hi @mcrot - I'm sure there are other errors that are not properly reported, but I guess this is an iterative process to fix those...

**Review by mcrot — DISMISSED** [review]
Great, thank you! Yes, let's refine this step-by-step and this is already quite good, I think.

**Comment by mcrot** [comment]
There is no change in the Changelog file yet. Will this be 0.97.6 or 0.98.0? It changes the API somehow.

**Comment by pastewka** [comment]
I think it should be 0.98.0 - will add the change log

**Comment by pastewka** [comment]
I've added a changelog, can you reapprove?

**Review by AntoineSIMTEK — APPROVED** [review]

**Pull request merged**
