### PR TITLE
nan hadling of sdsp function

### PR DESCRIPTION
**Pull request by pstr16**
Check the threshold (if the probability distribution has enough entries) and if the threshold is not reached, create a nan (inf are excluded in this way) and finally perform np.nanmean, so that the the mean over all real numbers gets calculated and nans get excluded.

### CODE REVIEW

**Comment by AntoineSIMTEK** [comment]
Additionally, could you add a test ensuring this functionality is working properly also in future ?

**Review by AntoineSIMTEK — APPROVED** [review]

**Review by AntoineSIMTEK — APPROVED** [review]
Looks good

**Comment by AntoineSIMTEK** [comment]
@pastewka  Any idea why there areno test-runs with this PR ?

**Comment by pastewka** [comment]
No idea why there are no tests... Please merge and fix failing tests then.

**Pull request merged**
