### PR TITLE
Bug/model variance half derivative

### PR DESCRIPTION
**Pull request by sannant**

### CODE REVIEW

**Comment by pastewka** [comment]
Did you just remove the half derivative?

**Comment by pastewka** [comment]
CI appears to fail

**Comment by sannant** [comment]
I removed a specific function for the half derivative which got redundant because I implemented a general function (derivative of arbitrary order). 
I corrected some bugs only in the general one

**Comment by sannant** [comment]
Yes it is a weird issue with meson: 

Run python3 -m pip install ".[test]"
Defaulting to user installation because normal site-packages is not writeable
Processing /home/runner/work/SurfaceTopography/SurfaceTopography
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      
      meson-python: error: Could not find meson version 0.[6](https://github.com/ContactEngineering/SurfaceTopography/actions/runs/5229097909/jobs/9441880864?pr=317#step:5:7)3.3 or newer, found 0.61.2
      meson-python: error: .
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I do not understand why this happens on this branch only

**Comment by sannant** [comment]
maybe something broke in the build system. 

Shall we instore dependabot and/or weekly scheduled testing here as well?

**Pull request merged**
