### PR TITLE
WIP: Making MitutoyoReader process a wider variety of xlsx-Files

### PR DESCRIPTION
**Pull request by jotelha**

### CODE REVIEW

**Comment by jotelha** [comment]
@pastewka the extended Mitutoyo test cases run fine locally, there seems to be something broken in the CI test workflows' dependencies, they throw

```
ERROR: muspectre==0.26.1 from https://files.pythonhosted.org/packages/1b/64/98af38bd8b8b5e845e8b87cfdbceac1833f29c97d160805e1bc08a70389e/muspectre-0.26.1.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by pastewka** [comment]
Why didn't you include the original Mitutoyo file?

**Review by pastewka — CHANGES_REQUESTED** [review]
- Please add original Mitutoyo file and include in tests
- Please add change log entry

Looks good otherwise

**Comment by pastewka** [comment]
I fixed the downstream muspectre package

**Comment by jotelha** [comment]
> - Please add original Mitutoyo file and include in tests
it's in there, 'mitutoyo_2_mock.xlsx'.
> - Please add change log entry
> 
> Looks good otherwise

**Review by pastewka — APPROVED** [review]

**Pull request merged**
