### PR TITLE
MAINT: New style reader for X3P

### PR DESCRIPTION
**Pull request by pastewka**
This PR converts the X3P reader to a new style reader that separats reading of metadata and data.

### CODE REVIEW

**Comment by jotelha** [comment]
I assume the tests would have run through this time if they hadn't been cancelled after 30 min...

**Review by jotelha — APPROVED** [review]

**Comment by jotelha** [comment]
Hm, there are apparently some scenarios where almost all tests are skipped, i.e. 
https://github.com/ContactEngineering/SurfaceTopography/actions/runs/3509706086/jobs/5878989185 with `---------------- 19 passed, 1351 skipped, 2 warnings in 12.85s -----------------` while others run way too slow, `https://github.com/ContactEngineering/SurfaceTopography/actions/runs/3509706218/jobs/5878989874`

**Comment by pastewka** [comment]
No, the tests stall - I don't understand why. I limited it to 30 minutes because the ran for 6 hours before being terminated earlier.

**Comment by pastewka** [comment]
Hi @jotelha - can you review this. I've disabled the test that seems to cause the problem. It may be a bug in parallel NetCDF.

**Comment by pastewka** [comment]
Okay, I think I understand what was happening. I've seen this before but not on a regular basis.

We start MPI tests with 4 CPUs. Then the tests run with 1 or 4 MPI processes.

**Review by jotelha — APPROVED** [review]

**Comment by jotelha** [comment]
Was that undeterministic whether they run with 1 or 4 processes?

**Comment by pastewka** [comment]
> Was that undeterministic whether they run with 1 or 4 processes?

Yes. For some reason that I don't understand. It looked to me like 3 of four processes wait for the 4th to finish something, which then locks the whole thing if the 4th for some reason crashed or took a turn into a direction that didn't call the respective MPI function.

With I/O, this may also have been related to the fact that all processes essentially wrote to the same file.

**Pull request merged**
