### PR TITLE
BUILD: Proper version discovery

### PR DESCRIPTION
**Pull request by pastewka**

### CODE REVIEW

**Comment by jotelha** [comment]
```bash
python3 -m pip install .[test]
```
fails with
```
Created wheel for surfacetopography: filename=surfacetopography-900d898-cp38-cp38-linux_x86_64.whl size=687857 sha256=a509a59ba907485aca0ce8c383c448d764f5fb771d0d3bbe58b8b599c3012d94
  Stored in directory: /tmp/pip-ephem-wheel-cache-j9ubotz1/wheels/13/2b/d6/60241f95f2460c0b6b67afed50d63a02668a4e77ac4ff47517
  WARNING: Built wheel for surfacetopography is invalid: Metadata 1.2 mandates PEP 440 version, but '900d898' is not
```
Looks like it's trying to use some shortened hash as version. 

Why use a custom script instead of `setuptools_scm` for retrieving the version anyway?
Have used it in `setup.py` a lot, but should work for `.toml` projects as well (https://github.com/pypa/setuptools_scm#pyprojecttoml-usage).

**Comment by pastewka** [comment]
Can you say what you did exactly? Is this within a checked out repository?

**Comment by pastewka** [comment]
Sorry, I see that you are refering to the CI. The problem is that the CI does not seem to pull tags. I've just pushed an update, let's see if this fixes it.

**Comment by jotelha** [comment]
You mean with respect to version discovery? Yes, in a checked out git repo. There are a few bits necessary, I can only show for `setup.py`, will need to look into how to translate that to this non-procedural toml approach:

At the core are such lines,
```
    use_scm_version={
        "local_scheme": local_scheme,
        "root": '.',
        "relative_to": __file__,
        "write_to": os.path.join(
            "dtool_lookup_gui", "version.py"),
    },
```
in the `setup.py`, i.e. https://github.com/livMatS/dtool-lookup-gui/blob/50602ab7b6275ec6f47f89c9785cc36fe6ba55c8/setup.py#L62-L68.

`local_scheme` just strips the cryptic suffix for the local (dirty),
```
def local_scheme(version):
    """Skip the local version (eg. +xyz of 0.6.1.dev4+gdf99fe2)
    to be able to upload to Test PyPI"""
    return ""
```
i.e. https://github.com/livMatS/dtool-lookup-gui/blob/50602ab7b6275ec6f47f89c9785cc36fe6ba55c8/setup.py#L41-L44,
```bash
pip install setuptools_scm
version=$(SETUPTOOLS_SCM_DEBUG=1 python setup.py --version)
```
prints the version, i.e. https://github.com/livMatS/dtool-lookup-gui/blob/50602ab7b6275ec6f47f89c9785cc36fe6ba55c8/.github/workflows/build-and-publish.yml#L116-L117

Won't work if the repo is shallow, output will look like this,
```console
$ python setup.py --version
/path/to/venv/lib/python3.8/site-packages/setuptools_scm/git.py:135: UserWarning: "/path/to/repo" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
0.1.dev1
```
and needs history and tags to work properly, i.e.
```bash
git fetch --prune --unshallow
git fetch --depth=1 origin +refs/tags/*:refs/tags/*
```
to work properly,
```console
$ python setup.py --version
0.6.3.dev11
```

With `SETUPTOOLS_SCM_DEBUG=1` it prints all the the stuff it does to determine the version, essentially a few `git` commands,
```
...
cmd:
     git --git-dir /home/jotelha/tmp/dtool-lookup-gui-full/.git describe --dirty --tags --long --match "*[0-9]*"
 in: /home/jotelha/tmp/dtool-lookup-gui-full
out:
     0.6.2-11-g50602ab

----
cmd:
     git --git-dir /home/jotelha/tmp/dtool-lookup-gui-full/.git rev-parse --abbrev-ref HEAD
 in: /home/jotelha/tmp/dtool-lookup-gui-full
out:
     master

----
cmd:
     git --git-dir /home/jotelha/tmp/dtool-lookup-gui-full/.git -c log.showSignature=false log -n 1 HEAD --format=%cI
 in: /home/jotelha/tmp/dtool-lookup-gui-full
out:
     2022-11-21T14:33:06+01:00
tag 0.6.2
tag '0.6.2' parsed to {'version': '0.6.2', 'prefix': '', 'suffix': ''}
version pre parse 0.6.2
version <Version('0.6.2')>
version 0.6.2 -> 0.6.2
EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') <ScmVersion 0.6.2 dist=11 node=g50602ab dirty=False branch=master>
scm version <ScmVersion 0.6.2 dist=11 node=g50602ab dirty=False branch=master>
config {'version_scheme': 'guess-next-dev', 'local_scheme': <function local_scheme at 0x7f04f6e65d30>}
ep found: guess-next-dev
version 0.6.3.dev11
local_version 
0.6.3.dev11
```
and that looks somewhat similar to  what the custom version discovery script here does.

**Comment by pastewka** [comment]
We no longer have a `setup.py`.

**Comment by jotelha** [comment]
I am aware of that, but you asked to describe,

> Can you say what you did exactly? Is this within a checked out repository?

and that's what I did ...

**Comment by pastewka** [comment]
Hi @jotelha - can you review again. I disabled the test that depends on reading containers from contact.engineering - will reenable when the certificate issue is resolved.

**Review by jotelha — APPROVED** [review]

**Comment by mcrot** [comment]
The certificate issue should be resolved now.

**Pull request merged**
